/*
 * Copyright 2018 Jack Humbert <jack.humb@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

/* USB Device descriptor parameter */
#define VENDOR_ID 0xFEED
#define PRODUCT_ID 0x6060
#define DEVICE_VER 0x0001
#define MANUFACTURER Kennydf
#define PRODUCT 1mytest
#define DESCRIPTION A custom keyboard

//#undef MATRIX_ROWS
//#undef MATRIX_COLS
/* key matrix size */

/*
 * Keyboard Matrix Assignments
 *
 * Change this to how you wired your keyboard
 * COLS: AVR pins used for columns, left to right
 * ROWS: AVR pins used for rows, top to bottom
 * DIODE_DIRECTION: COL2ROW = COL = Anode (+), ROW = Cathode (-, marked on diode)
 *                  ROW2COL = ROW = Anode (+), COL = Cathode (-, marked on diode)
 *
*/
#define DEBUG_MATRIX_SCAN_RATE
//아래거는 411용




#define MATRIX_ROWS 6
#define MATRIX_COLS 21


#define MATRIX_ROW_PINS { A0,A1,A2,A3,A6,A7 }
#define MATRIX_COL_PINS {  B0,B1, B2, B10,B11,B12,B13,B14,B15,A8,A9,A10, A13, A14, A15,B3,B4, B5,B8,B9,A4   }




//#define MATRIX_ROW_PINS { A2,A1,A0,C15,C14,C13 }
//#define MATRIX_COL_PINS {  B4,B3, A10, A9,A8,B15,B14,B13,B12,A4,A5,A15, B5, B8, B9,A3,A6, A7,B0,B1,B10   }
//A11, A12, A15, B5, B8, B9,A3,A6, A7,B0,B1,B10B11



/*

#define MATRIX_ROWS 1
#define MATRIX_COLS 3

#define MATRIX_ROW_PINS { A2 }
#define MATRIX_COL_PINS {  B4,B3, A10}

*/



//아래거는 303 용
//#define MATRIX_ROW_PINS { A2,A1,A0,A3,A4,A5}
//#define MATRIX_COL_PINS {  B4,B3, A10, A9,A8,B15,B14,B13,B12,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12  }

///#define MATRIX_ROW_PINS { B12,B13, B14, B15,B11,B10 }
//#define MATRIX_COL_PINS { A1,	A2,A3,	A6,	A7,A10,	A11,	A12,	A15,	C3,C2,C1,C0,C15,C14,	B2,	B1,	B0,	C5,	C4,	A0}
#define DIODE_DIRECTION COL2ROW
//#define MATRIX_IO_DELAY 35


//#define MUSIC_MAP
#undef AUDIO_VOICES
#undef C6_AUDIO

#define USB_POLLING_INTERVAL_MS 1
#ifdef AUDIO_ENABLE
  #define STARTUP_SONG SONG(STARTUP_SOUND)
#endif


#define DAC_SAMPLE_MAX 60000U
#define ADA_REST MUSICAL_NOTE(_REST,0.0001)


#define B__N(note) MUSICAL_NOTE(note,1024)
#define W__N(note) MUSICAL_NOTE(note,512)
#define H__N(note) MUSICAL_NOTE(note,256)
#define Q__N(note) MUSICAL_NOTE(note,128)
#define E__N(note) MUSICAL_NOTE(note,64)
#define S__N(note) MUSICAL_NOTE(note,32)
#define BD_N(note) MUSICAL_NOTE(note,1536)
#define WD_N(note) MUSICAL_NOTE(note,768)
#define HD_N(note) MUSICAL_NOTE(note,384)
#define QD_N(note) MUSICAL_NOTE(note,192)
#define ED_N(note) MUSICAL_NOTE(note,96)
#define SD_N(note) MUSICAL_NOTE(note,48)
#define TS_N(note) MUSICAL_NOTE(note,16)
#define SH_N(note) MUSICAL_NOTE(note,5)

//#define gimoddi H__NOTE(_D6), HD_NOTE(_G6), Q__NOTE(_F6), H__NOTE(_E6), H__NOTE(_G6), H__NOTE(_D6), H__NOTE(_B5), H__NOTE(_D6), H__NOTE(_G6), Q__NOTE(_A6), Q__NOTE(_B6), HD_NOTE(_C7), Q__NOTE(_B6), B__NOTE(_A6),
#define gimoddi TS_N(_A6), ADA_REST, TS_N(_C7), ADA_REST, S__N(_A6), ADA_REST, E__N(_E7), ADA_REST, E__N(_F7), ADA_REST, E__N(_D7), ADA_REST, S__N(_E7), ADA_REST, S__N(_A6), ADA_REST, E__N(_E7), ADA_REST, E__N(_F7), ADA_REST, E__N(_D7), ADA_REST, S__N(_E7), ADA_REST, S__N(_A6), ADA_REST, E__N(_E7), ADA_REST, E__N(_F7), ADA_REST, E__N(_D7), ADA_REST, E__N(_E7), ADA_REST, E__N(_C7), ADA_REST, E__N(_D7), ADA_REST, E__N(_B6), ADA_REST, S__N(_C7), ADA_REST, S__N(_FS6), ADA_REST, E__N(_CS7), ADA_REST, E__N(_D7), ADA_REST, E__N(_B6), ADA_REST, E__N(_CS7), ADA_REST, E__N(_CS7), ADA_REST, E__N(_D7), ADA_REST, E__N(_B7), ADA_REST, S__N(_FS6), ADA_REST, S__N(_FS6), ADA_REST, E__N(_CS7), ADA_REST, E__N(_D7), ADA_REST, E__N(_B6), ADA_REST, E__N(_CS7), ADA_REST, E__N(_CS7), ADA_REST, E__N(_D7), ADA_REST, E__N(_B6), ADA_REST, S__N(_FS6), ADA_REST, S__N(_FS6), ADA_REST, E__N(_CS7), ADA_REST, E__N(_D7), ADA_REST, E__N(_B6), ADA_REST, E__N(_CS7), ADA_REST, E__N(_CS7), ADA_REST, E__N(_D7), ADA_REST, E__N(_B6), ADA_REST, TS_N(_FS6), ADA_REST, TS_N(_FS6), ADA_REST, S__N(_FS6), ADA_REST, E__N(_CS7), ADA_REST, ED_N(_D7), ADA_REST, S__N(_B6), ADA_REST, H__N(_CS7), ADA_REST, TS_N(_A6), ADA_REST, TS_N(_A6), ADA_REST, S__N(_A6), ADA_REST, E__N(_E7), ADA_REST, E__N(_F7), ADA_REST, E__N(_D7), ADA_REST, E__N(_E7), ADA_REST, E__N(_E7), ADA_REST, E__N(_F7), ADA_REST, E__N(_D7), ADA_REST, S__N(_A6), ADA_REST, S__N(_A6), ADA_REST, E__N(_E7), ADA_REST, E__N(_F7), ADA_REST, E__N(_D7), ADA_REST, E__N(_E7), ADA_REST, E__N(_E7), ADA_REST, E__N(_F7), ADA_REST, E__N(_D7), ADA_REST, S__N(_A6), ADA_REST, S__N(_A6), ADA_REST, E__N(_E7), ADA_REST, E__N(_F7)


#define gimoddi1 ADA_REST, E__N(_D7), ADA_REST, E__N(_E7), ADA_REST, E__N(_E7), ADA_REST, E__N(_F7), ADA_REST, E__N(_D7), ADA_REST, TS_N(_A6), ADA_REST, TS_N(_A6), ADA_REST, S__N(_A6), ADA_REST, E__N(_E7), ADA_REST, ED_N(_F7), ADA_REST, S__N(_D7), ADA_REST, H__N(_E7), ADA_REST, S__N(_REST), ADA_REST, S__N(_CS7), ADA_REST, S__N(_B6), ADA_REST, S__N(_A6), ADA_REST, S__N(_GS6), ADA_REST, S__N(_FS6), ADA_REST, S__N(_GS6), ADA_REST, S__N(_A6), ADA_REST, S__N(_E7), ADA_REST, ED_N(_E7), ADA_REST, S__N(_B6), ADA_REST, E__N(_CS7), ADA_REST, E__N(_B6), ADA_REST, S__N(_FS6), ADA_REST, S__N(_GS6), ADA_REST, S__N(_A6), ADA_REST, S__N(_CS7), ADA_REST, S__N(_B6), ADA_REST, S__N(_A6), ADA_REST, S__N(_GS6), ADA_REST, S__N(_E7), ADA_REST, S__N(_E7), ADA_REST, S__N(_FS7), ADA_REST, SD_N(_E7), ADA_REST, TS_N(_B6), ADA_REST, E__N(_CS7), ADA_REST, TS_N(_A6), ADA_REST, TS_N(_B6), ADA_REST, TS_N(_CS7), ADA_REST, TS_N(_D7), ADA_REST, S__N(_E7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, S__N(_B6), ADA_REST, S__N(_A6), ADA_REST, S__N(_B6), ADA_REST, S__N(_C7), ADA_REST, S__N(_E7), ADA_REST, SH_N(_E7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, SD_N(_D7), ADA_REST, TS_N(_G7), ADA_REST, E__N(_G7), ADA_REST, E__N(_D7), ADA_REST, S__N(_E7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, S__N(_B6), ADA_REST, S__N(_A6), ADA_REST, S__N(_B6), ADA_REST, S__N(_C7), ADA_REST, S__N(_E7), ADA_REST, ED_N(_D7), ADA_REST, S__N(_B6), ADA_REST, ED_N(_E7), ADA_REST, S__N(_REST), ADA_REST, S__N(_E7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, S__N(_B6), ADA_REST, S__N(_A6), ADA_REST, E__N(_C7), ADA_REST, S__N(_E7), ADA_REST, SH_N(_E7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, S__N(_B6), ADA_REST, S__N(_C7), ADA_REST, S__N(_D7), ADA_REST, S__N(_REST), ADA_REST, E__N(_G7), ADA_REST, S__N(_E7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, S__N(_B6), ADA_REST



#define gimoddi2 S__N(_A6), ADA_REST, S__N(_B6), ADA_REST, S__N(_C7), ADA_REST, S__N(_E7), ADA_REST, ED_N(_D7), ADA_REST, S__N(_B6), ADA_REST, ED_N(_E7), ADA_REST, TS_N(_D7), ADA_REST, TS_N(_E7), ADA_REST, ED_N(_F7), ADA_REST, TS_N(_D7), ADA_REST, TS_N(_F7), ADA_REST, S__N(_FS7), ADA_REST, S__N(_DS7), ADA_REST, S__N(_F7), ADA_REST, S__N(_A7), ADA_REST, ED_N(_A7), ADA_REST, S__N(_GS7), ADA_REST, ED_N(_G7), ADA_REST, S__N(_C7), ADA_REST, ED_N(_C7), ADA_REST, S__N(_D7), ADA_REST, ED_N(_D7), ADA_REST, S__N(_F7), ADA_REST, ED_N(_F7), ADA_REST, S__N(_E7), ADA_REST, ED_N(_E7), ADA_REST, S__N(_C7), ADA_REST, ED_N(_C7), ADA_REST, S__N(_C7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, S__N(_B6), ADA_REST, S__N(_A6), ADA_REST, ED_N(_A6), ADA_REST, S__N(_G6), ADA_REST, ED_N(_G6), ADA_REST, S__N(_C7), ADA_REST, S__N(_C7), ADA_REST, S__N(_F6), ADA_REST, S__N(_A6), ADA_REST, S__N(_D7), ADA_REST, S__N(_D7), ADA_REST, S__N(_G6), ADA_REST, S__N(_B6), ADA_REST, S__N(_F7), ADA_REST, ED_N(_F7), ADA_REST

#define gimoddi3 S__N(_E7), ADA_REST, E__N(_E7), ADA_REST, S__N(_REST), ADA_REST, S__N(_C7), ADA_REST, ED_N(_C7), ADA_REST, S__N(_C7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, S__N(_D7), ADA_REST, S__N(_F7), ADA_REST, ED_N(_A7), ADA_REST, S__N(_GS7), ADA_REST, ED_N(_GS7), ADA_REST, S__N(_DS7), ADA_REST, ED_N(_DS7), ADA_REST, S__N(_F7), ADA_REST, ED_N(_F7), ADA_REST, S__N(_GS7), ADA_REST, ED_N(_GS7), ADA_REST, S__N(_G7), ADA_REST, ED_N(_G7), ADA_REST, S__N(_DS7), ADA_REST, ED_N(_DS7), ADA_REST, S__N(_DS7), ADA_REST, S__N(_F7), ADA_REST, S__N(_DS7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, ED_N(_C7), ADA_REST, S__N(_AS6), ADA_REST, ED_N(_AS6), ADA_REST, S__N(_DS7), ADA_REST, ED_N(_DS7), ADA_REST, S__N(_F7), ADA_REST, ED_N(_F7), ADA_REST, S__N(_GS7), ADA_REST, ED_N(_GS7), ADA_REST, S__N(_G7), ADA_REST, ED_N(_G7), ADA_REST, S__N(_E7), ADA_REST, ED_N(_E7), ADA_REST

#define gimoddi4 MUSICAL_NOTE(_A6,22.5), ADA_REST, MUSICAL_NOTE(_C7,22.5), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_F7,90), ADA_REST, MUSICAL_NOTE(_D7,90), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_F7,90), ADA_REST, MUSICAL_NOTE(_D7,90), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_F7,90), ADA_REST, MUSICAL_NOTE(_D7,90), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_C7,90), ADA_REST, MUSICAL_NOTE(_D7,90), ADA_REST, MUSICAL_NOTE(_B6,90), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_FS5,45), ADA_REST, MUSICAL_NOTE(_CS6,90), ADA_REST, MUSICAL_NOTE(_D6,90), ADA_REST, MUSICAL_NOTE(_B5,90), ADA_REST, MUSICAL_NOTE(_CS6,90), ADA_REST, MUSICAL_NOTE(_CS6,90), ADA_REST, MUSICAL_NOTE(_D6,90), ADA_REST, MUSICAL_NOTE(_B5,90), ADA_REST, MUSICAL_NOTE(_FS5,45), ADA_REST, MUSICAL_NOTE(_FS5,45), ADA_REST, MUSICAL_NOTE(_CS6,90), ADA_REST, MUSICAL_NOTE(_D6,90), ADA_REST, MUSICAL_NOTE(_B5,90), ADA_REST, MUSICAL_NOTE(_CS6,90), ADA_REST, MUSICAL_NOTE(_CS6,90), ADA_REST, MUSICAL_NOTE(_D6,90), ADA_REST, MUSICAL_NOTE(_B5,90), ADA_REST, MUSICAL_NOTE(_FS5,45), ADA_REST, MUSICAL_NOTE(_FS5,45), ADA_REST, MUSICAL_NOTE(_CS6,90), ADA_REST, MUSICAL_NOTE(_D6,90), ADA_REST, MUSICAL_NOTE(_B5,90), ADA_REST, MUSICAL_NOTE(_CS6,90), ADA_REST, MUSICAL_NOTE(_CS6,90), ADA_REST, MUSICAL_NOTE(_D6,90), ADA_REST, MUSICAL_NOTE(_B5,90), ADA_REST, MUSICAL_NOTE(_FS5,22.5), ADA_REST, MUSICAL_NOTE(_FS5,22.5), ADA_REST, MUSICAL_NOTE(_FS5,45), ADA_REST, MUSICAL_NOTE(_CS6,90), ADA_REST, MUSICAL_NOTE(_D6,135), ADA_REST, MUSICAL_NOTE(_B5,45), ADA_REST, MUSICAL_NOTE(_CS6,360), ADA_REST, MUSICAL_NOTE(_A6,22.5), ADA_REST, MUSICAL_NOTE(_A6,22.5), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_F7,90), ADA_REST, MUSICAL_NOTE(_D7,90), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_F7,90), ADA_REST, MUSICAL_NOTE(_D7,90), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_F7,90), ADA_REST, MUSICAL_NOTE(_D7,90), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_F7,90), ADA_REST, MUSICAL_NOTE(_D7,90), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_F7,90), ADA_REST, MUSICAL_NOTE(_D7,90), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_F7,90), ADA_REST, MUSICAL_NOTE(_D7,90), ADA_REST, MUSICAL_NOTE(_A6,22.5), ADA_REST, MUSICAL_NOTE(_A6,22.5), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_F7,135), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_E7,360), ADA_REST, MUSICAL_NOTE(_REST,45), ADA_REST, MUSICAL_NOTE(_CS7,45), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_GS6,45), ADA_REST, MUSICAL_NOTE(_FS6,45), ADA_REST, MUSICAL_NOTE(_GS6,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_E7,135), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_CS7,90), ADA_REST, MUSICAL_NOTE(_B6,90), ADA_REST, MUSICAL_NOTE(_FS6,45), ADA_REST, MUSICAL_NOTE(_GS6,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_CS7,45), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_GS6,45), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_FS7,45), ADA_REST, MUSICAL_NOTE(_E7,67.5), ADA_REST, MUSICAL_NOTE(_B6,22.5), ADA_REST, MUSICAL_NOTE(_CS7,90), ADA_REST, MUSICAL_NOTE(_A6,22.5), ADA_REST, MUSICAL_NOTE(_B6,22.5), ADA_REST, MUSICAL_NOTE(_CS7,22.5), ADA_REST, MUSICAL_NOTE(_D7,22.5), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_E7,18), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_D7,67.5), ADA_REST, MUSICAL_NOTE(_G7,22.5), ADA_REST, MUSICAL_NOTE(_G7,90), ADA_REST, MUSICAL_NOTE(_D7,90), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_D7,135), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_E7,135), ADA_REST, MUSICAL_NOTE(_REST,45), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_C7,90), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_E7,18), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_REST,45), ADA_REST, MUSICAL_NOTE(_G7,90), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_G7,135), ADA_REST, MUSICAL_NOTE(_D6,45), ADA_REST, MUSICAL_NOTE(_E7,135), ADA_REST, MUSICAL_NOTE(_D7,22.5), ADA_REST, MUSICAL_NOTE(_E7,22.5), ADA_REST, MUSICAL_NOTE(_F7,135), ADA_REST, MUSICAL_NOTE(_D7,22.5), ADA_REST, MUSICAL_NOTE(_F7,22.5), ADA_REST, MUSICAL_NOTE(_FS7,45), ADA_REST, MUSICAL_NOTE(_DS7,45), ADA_REST, MUSICAL_NOTE(_F7,45), ADA_REST, MUSICAL_NOTE(_A7,45), ADA_REST, MUSICAL_NOTE(_A7,135), ADA_REST, MUSICAL_NOTE(_GS7,45), ADA_REST, MUSICAL_NOTE(_GS7,135), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_C7,135), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_D7,135), ADA_REST, MUSICAL_NOTE(_F7,45), ADA_REST, MUSICAL_NOTE(_F7,135), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_E7,135), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_C7,135), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_A6,135), ADA_REST, MUSICAL_NOTE(_G6,45), ADA_REST, MUSICAL_NOTE(_G6,135), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_F6,45), ADA_REST, MUSICAL_NOTE(_A6,45), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_G6,45), ADA_REST, MUSICAL_NOTE(_B6,45), ADA_REST, MUSICAL_NOTE(_F7,45), ADA_REST, MUSICAL_NOTE(_F7,135), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_E7,90), ADA_REST, MUSICAL_NOTE(_REST,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_C7,135), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_F7,45), ADA_REST, MUSICAL_NOTE(_A7,135), ADA_REST, MUSICAL_NOTE(_GS7,45), ADA_REST, MUSICAL_NOTE(_GS7,135), ADA_REST, MUSICAL_NOTE(_DS7,45), ADA_REST, MUSICAL_NOTE(_DS7,135), ADA_REST, MUSICAL_NOTE(_F7,45), ADA_REST, MUSICAL_NOTE(_F7,135), ADA_REST, MUSICAL_NOTE(_GS7,45), ADA_REST, MUSICAL_NOTE(_GS7,135), ADA_REST, MUSICAL_NOTE(_G7,45), ADA_REST, MUSICAL_NOTE(_G7,135), ADA_REST, MUSICAL_NOTE(_DS7,45), ADA_REST, MUSICAL_NOTE(_DS7,135), ADA_REST, MUSICAL_NOTE(_DS7,45), ADA_REST, MUSICAL_NOTE(_F7,45), ADA_REST, MUSICAL_NOTE(_DS7,45), ADA_REST, MUSICAL_NOTE(_D7,45), ADA_REST, MUSICAL_NOTE(_C7,45), ADA_REST, MUSICAL_NOTE(_C7,135), ADA_REST, MUSICAL_NOTE(_AS6,45), ADA_REST, MUSICAL_NOTE(_AS6,135), ADA_REST, MUSICAL_NOTE(_DS7,45), ADA_REST, MUSICAL_NOTE(_DS7,135), ADA_REST, MUSICAL_NOTE(_F7,45), ADA_REST, MUSICAL_NOTE(_F7,135), ADA_REST, MUSICAL_NOTE(_GS7,45), ADA_REST, MUSICAL_NOTE(_GS7,135), ADA_REST, MUSICAL_NOTE(_G7,45), ADA_REST, MUSICAL_NOTE(_G7,135), ADA_REST, MUSICAL_NOTE(_E7,45), ADA_REST, MUSICAL_NOTE(_E7,135), ADA_REST,




#define TAP_CODE_DELAY 10

//, S__N(_C7), ADA_REST, S__N(_B6), ADA_REST, S__N(_C7), ADA_REST, S__N(_D7), ADA_REST, S__N(_REST7), ADA_REST, E__N(_G7), ADA_REST, S__N(_E7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, S__N(_B6), ADA_REST, S__N(_A6), ADA_REST, S__N(_B6), ADA_REST, S__N(_C7), ADA_REST, S__N(_E7), ADA_REST, ED_N(_D7), ADA_REST, S__N(_B6), ADA_REST, ED_N(_E7), ADA_REST, TS_N(_D7), ADA_REST, TS_N(_E7), ADA_REST, ED_N(_F7), ADA_REST, TS_N(_D7), ADA_REST, TS_N(_F7), ADA_REST, S__N(_FS7), ADA_REST, S__N(_DS7), ADA_REST, S__N(_F7), ADA_REST, S__N(_A7), ADA_REST, ED_N(_A7), ADA_REST, S__N(_GS7), ADA_REST, ED_N(_G7), ADA_REST, S__N(_C7), ADA_REST, ED_N(_C7), ADA_REST, S__N(_D7), ADA_REST, ED_N(_D7), ADA_REST, S__N(_F7), ADA_REST, ED_N(_F7), ADA_REST, S__N(_E7), ADA_REST, ED_N(_E7), ADA_REST, S__N(_C7), ADA_REST, ED_N(_C7), ADA_REST, S__N(_C7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, S__N(_B6), ADA_REST, S__N(_A6), ADA_REST, ED_N(_A6), ADA_REST, S__N(_G6), ADA_REST, ED_N(_G6), ADA_REST, S__N(_C7), ADA_REST, S__N(_C7), ADA_REST, S__N(_F6), ADA_REST, S__N(_A6), ADA_REST, S__N(_D7), ADA_REST, S__N(_D7), ADA_REST, S__N(_G6), ADA_REST, S__N(_B6), ADA_REST, S__N(_F7), ADA_REST, ED_N(_F7), ADA_REST, S__N(_E7), ADA_REST, E__N(_E7), ADA_REST, S__N(_REST), ADA_REST, S__N(_C7), ADA_REST, ED_N(_C7), ADA_REST, S__N(_C7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, S__N(_D7), ADA_REST, S__N(_F7), ADA_REST, ED_N(_A7), ADA_REST, S__N(_GS7), ADA_REST, ED_N(_GS7), ADA_REST, S__N(_DS7), ADA_REST, ED_N(_DS7), ADA_REST, S__N(_F7), ADA_REST, ED_N(_F7), ADA_REST, S__N(_GS7), ADA_REST, ED_N(_GS7), ADA_REST, S__N(_G7), ADA_REST, ED_N(_G7), ADA_REST, S__N(_DS7), ADA_REST, ED_N(_DS7), ADA_REST, S__N(_DS7), ADA_REST, S__N(_F7), ADA_REST, S__N(_DS7), ADA_REST, S__N(_D7), ADA_REST, S__N(_C7), ADA_REST, ED_N(_C7), ADA_REST, S__N(_AS6), ADA_REST, ED_N(_AS6), ADA_REST, S__N(_DS7), ADA_REST, ED_N(_DS7), ADA_REST, S__N(_F7), ADA_REST, ED_N(_F7), ADA_REST, S__N(_GS7), ADA_REST, ED_N(_GS7), ADA_REST, S__N(_G7), ADA_REST, ED_N(_G7), ADA_REST, S__N(_E7), ADA_REST, ED_N(_E7), ADA_REST


/* Mechanical locking support. Use KC_LCAP, KC_LNUM or KC_LSCR instead in keymap */
//#define LOCKING_SUPPORT_ENABLE
/* Locking resynchronize hack */
//#define LOCKING_RESYNC_ENABLE

/*
 * Force NKRO
 *
 * Force NKRO (nKey Rollover) to be enabled by default, regardless of the saved
 * state in the bootmagic EEPROM settings. (Note that NKRO must be enabled in the
 * makefile for this to work.)
 *
 * If forced on, NKRO can be disabled via magic key (default = LShift+RShift+N)
 * until the next keyboard reset.
 *
 * NKRO may prevent your keystrokes from being detected in the BIOS, but it is
 * fully operational during normal computer usage.
 *
 * For a less heavy-handed approach, enable NKRO via magic key (LShift+RShift+N)
 * or via bootmagic (hold SPACE+N while plugging in the keyboard). Once set by
 * bootmagic, NKRO mode will always be enabled until it is toggled again during a
 * power-up.
 *
 */
//#define FORCE_NKRO

/*
 * Feature disable options
 *  These options are also useful to firmware size reduction.
 */

/* disable debug print */
//#define NO_DEBUG

/* disable print */
//#define NO_PRINT

/* disable action features */
//#define NO_ACTION_LAYER
//#define NO_ACTION_TAPPING
//#define NO_ACTION_ONESHOT
//#define NO_ACTION_MACRO
//#define NO_ACTION_FUNCTION

/*
 * MIDI options
 */

/* Prevent use of disabled MIDI features in the keymap */
//#define MIDI_ENABLE_STRICT 1

/* enable basic MIDI features:
   - MIDI notes can be sent when in Music mode is on
*/
//#define MIDI_BASIC

/* enable advanced MIDI features:
   - MIDI notes can be added to the keymap
   - Octave shift and transpose
   - Virtual sustain, portamento, and modulation wheel
   - etc.
*/
//#define MIDI_ADVANCED

/* override number of MIDI tone keycodes (each octave adds 12 keycodes and allocates 12 bytes) */
//#define MIDI_TONE_KEYCODE_OCTAVES 1

//#define EECONFIG_RGB_MATRIX (uint32_t *)28


// #define WS2812_LED_N 2
// #define RGBLED_NUM WS2812_LED_N
// #define WS2812_TIM_N 2
// #define WS2812_TIM_CH 2
// #define PORT_WS2812     GPIOA
// #define PIN_WS2812      1
// #define WS2812_DMA_STREAM STM32_DMA1_STREAM2  // DMA stream for TIMx_UP (look up in reference manual under DMA Channel selection)
//#define WS2812_DMA_CHANNEL 7                  // DMA channel for TIMx_UP
//#define WS2812_EXTERNAL_PULLUP

#define DRIVER_ADDR_1 0b1010000
#define DRIVER_ADDR_2 0b1010001 // this is here for compliancy reasons.

#define DRIVER_COUNT 2
#define DRIVER_1_LED_TOTAL 53
#define DRIVER_2_LED_TOTAL 51



#define DRIVER_LED_TOTAL (DRIVER_1_LED_TOTAL + DRIVER_2_LED_TOTAL)

#define RGB_MATRIX_KEYPRESSES
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_DISABLE_WHEN_USB_SUSPENDED true


#define RGB_MATRIX_LED_PROCESS_LIMIT 20
#define RGB_MATRIX_LED_FLUSH_LIMIT 20

//#define RGB_MATRIX_CENTER { 50, 39 }
#define IGNORE_MOD_TAP_INTERRUPT

#define TAPPING_TOGGLE  1

#define MOUSEKEY_INTERVAL       20
#define MOUSEKEY_DELAY          0
#define MOUSEKEY_TIME_TO_MAX    60
#define MOUSEKEY_MAX_SPEED      7
#define MOUSEKEY_WHEEL_DELAY 0
